### ISSUE TITLE
Freeze when loading product description

### ISSUE THREAD

**Issue by Cesarsk** [Cruel/freeShop#27]
When freeshop is loading a selected product's description (the part on the bottom screen), you can't do anything to undo the loading process; I think that should be improved, because you need to wait for the loading (sometimes it does not load anything, and you need to force-quit the application) until you can select another product.

Obviously these are not "issues" but "precautions".

**Comment by Cruel** [comment]
Well, the freezing and need to force-quit should be resolved. However, I'm not going to change it so you can do other things while the game info loads.

However, when I redo the game info page, I'm going to make the screens load in the background (like eShop does). So the game page should load really quickly since currently most the time is spent fetching the screenshots before it even shows anything.

**Comment by shad00m** [comment]
i still have this issue :(
it loads and loads but after like 5 minutes still nothing has happened ans i have to force close it

**Comment by Cruel** [comment]
Is that with all games, @shad00m ?
